fix(gateway): panic when using compression with streams
Using compression with a stream ends up in a panic today:

```
thread 'grafbase-gateway' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/unfold.rs:108:21:
Unfold must not be polled after it returned `Poll::Ready(None)`
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <futures_util::stream::unfold::Unfold<T,F,Fut> as futures_core::stream::Stream>::poll_next
   4: <multipart_stream::serializer::Serializer<S,E> as futures_core::stream::Stream>::poll_next
   5: <futures_util::stream::try_stream::MapOk<St,F> as futures_core::stream::Stream>::poll_next
   6: <axum_core::body::StreamBody<S> as http_body::Body>::poll_frame
   7: <http_body_util::combinators::map_err::MapErr<B,F> as http_body::Body>::poll_frame
   8: <tower_http::compression_utils::BodyIntoStream<B> as http_body::Body>::poll_frame
   9: <tower_http::compression::body::CompressionBody<B> as http_body::Body>::poll_frame
  10: <http_body_util::combinators::map_err::MapErr<B,F> as http_body::Body>::poll_frame
  11: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
  12: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  13: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  14: axum_server::server::Server<A>::serve::{{closure}}::{{closure}}::{{closure}}
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  18: tokio::runtime::context::scoped::Scoped<T>::set
  19: tokio::runtime::context::runtime::enter_runtime
  20: tokio::runtime::scheduler::multi_thread::worker::run
  21: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  22: tokio::runtime::task::core::Core<T,S>::poll
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
```

There is an issue for `tower-http` explaining that compressed stream doesn't work that well today:

https://github.com/tower-rs/tower-http/issues/292

So disabling it. Apollo Router team has implemented a solution by forking the codecs, so we might have to do the same later on.