fix: adjust parser code to support esm modules
Netlify are running into issues running `grafbase dump-config` because they've
got `"module": true` in their package.json.  They're getting the following
error:

```
Error: could not load grafbase/grafbase.config.ts
Caused by: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/abhiramaiyer/Gatsby/sdk/examples/connector-example/grafbase/grafbase.config.ts
require() of ES modules is not supported.
require() of /Users/abhiramaiyer/Gatsby/sdk/examples/connector-example/grafbase/grafbase.config.ts from /Users/abhiramaiyer/.grafbase/parser/parse-config.ts is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /Users/abhiramaiyer/Gatsby/sdk/examples/connector-example/package.json.
```

The only way I've managed to fix this is with a separate implementation of the
`parse-config.ts` file, and by passing a bunch more arguments in on the command
line.

I don't fully understand the problem here or like the solution - if anyone has
better ideas please speak up.